extends Node

const CHARACTER_CATALOG: CharacterDefinitionCatalog = preload("res://resources/characters/kaykit/character_catalog.tres")
const CHARACTER_VISUAL_SCENE: PackedScene = preload("res://scenes/characters/CharacterVisual.tscn")
const CharacterCompatibilityValidator := preload("res://scripts/characters/character_compatibility_validator.gd")
const CharacterAuditTool := preload("res://scripts/characters/character_audit_tool.gd")

@export var quit_on_finish: bool = false

var _errors: PackedStringArray = []
var _warnings: PackedStringArray = []
var _notes: PackedStringArray = []
var _visual_results: Array[Dictionary] = []

func _ready() -> void:
	call_deferred("_run_validation")

func _run_validation() -> void:
	_errors.clear()
	_warnings.clear()
	_notes.clear()
	_visual_results.clear()
	var definitions: Array[CharacterDefinition] = CHARACTER_CATALOG.get_enabled_definitions()
	var compatibility: Dictionary = CharacterCompatibilityValidator.validate_definitions(definitions)
	_errors.append_array(compatibility.errors)
	_warnings.append_array(compatibility.warnings)
	_notes.append_array(compatibility.get("notes", PackedStringArray()))
	for definition: CharacterDefinition in definitions:
		_validate_definition(definition)
	_write_reports(compatibility.audit)
	var summary: String = "CharacterValidationTest: %d errors, %d warnings, %d notes, %d definitions" % [_errors.size(), _warnings.size(), _notes.size(), definitions.size()]
	print(summary)
	for message: String in _errors:
		push_error(message)
	for message: String in _warnings:
		push_warning(message)
	for message: String in _notes:
		print("NOTE: %s" % message)
	if quit_on_finish:
		get_tree().quit(1 if not _errors.is_empty() else 0)

func _validate_definition(definition: CharacterDefinition) -> void:
	var visual: CharacterVisual = CHARACTER_VISUAL_SCENE.instantiate() as CharacterVisual
	add_child(visual)
	var ok: bool = visual.apply_definition(definition)
	var diagnostics: Dictionary = visual.get_diagnostics()
	_visual_results.append(diagnostics)
	if not ok:
		_errors.append("%s failed to apply definition." % definition.id)
	if visual.get_skeleton() == null:
		_errors.append("%s has no runtime skeleton." % definition.id)
	if diagnostics.get("sockets", PackedStringArray()).size() < 4:
		_errors.append("%s did not create all canonical attachment sockets." % definition.id)
	var available_actions: PackedStringArray = visual.get_available_actions()
	for action_id: String in ["idle", "walk", "run", "hit"]:
		if not available_actions.has(action_id):
			_errors.append("%s missing required runtime action %s." % [definition.id, action_id])
	for action_id: String in available_actions:
		if not visual.get_animation_controller().play_action(action_id):
			_errors.append("%s could not play action %s." % [definition.id, action_id])
	visual.queue_free()

func _write_reports(audit: Dictionary) -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path("res://reports/characters"))
	_write_text("res://reports/characters/kaykit_skeleton_compatibility.md", _build_skeleton_report(audit))
	_write_text("res://reports/characters/kaykit_animation_compatibility.md", _build_animation_report(audit))

func _build_skeleton_report(audit: Dictionary) -> String:
	var lines: PackedStringArray = [
		"# KayKit Skeleton Compatibility",
		"",
		"Generated by `CharacterValidationTest` from imported Godot resources.",
		"",
		"## Compatibility",
		"",
		"- Errors: %d" % audit.compatibility.errors.size(),
		"- Warnings: %d" % audit.compatibility.warnings.size(),
		"- Notes: %d" % audit.compatibility.get("notes", PackedStringArray()).size(),
		"- Reference character: `%s`" % audit.compatibility.reference_character_id,
		"- Policy: world movement is owned by `CharacterBody3D`; KayKit locomotion clips are prepared as runtime in-place animation copies.",
		"",
		"## Characters",
		"",
	]
	for character_id: String in audit.characters.keys():
		var character: Dictionary = audit.characters[character_id]
		lines.append("### %s" % character_id)
		lines.append("")
		lines.append("- Scene: `%s`" % character.scene_path)
		lines.append("- Root node: `%s`" % character.root_node_path)
		lines.append("- Skeleton path: `%s`" % character.skeleton_path)
		lines.append("- Bone count: `%s`" % character.bone_count)
		lines.append("- Root bone: `%s`" % character.root_bone)
		lines.append("- Height: `%.3f`" % character.height)
		lines.append("- Bottom Y: `%.3f`" % character.bottom_y)
		lines.append("- Forward direction: `%s`" % character.forward_direction)
		lines.append("- Socket bones: `%s`" % JSON.stringify(character.socket_bones))
		lines.append("- Body bones: `%s`" % JSON.stringify(character.body_bones))
		lines.append("- Bone names: `%s`" % ", ".join(character.bone_names))
		lines.append("")
	lines.append("## Runtime CharacterVisual Results")
	lines.append("")
	for result: Dictionary in _visual_results:
		lines.append("- `%s`: height `%.3f`, bones `%s`, sockets `%s`, loadout `%s`, items `%s`" % [
			result.get("id", ""),
			result.get("height", 0.0),
			result.get("bone_count", 0),
			", ".join(result.get("sockets", PackedStringArray())),
			result.get("loadout", ""),
			", ".join(result.get("installed_items", PackedStringArray())),
		])
	return "\n".join(lines) + "\n"

func _build_animation_report(audit: Dictionary) -> String:
	var lines: PackedStringArray = [
		"# KayKit Animation Compatibility",
		"",
		"Generated by `CharacterValidationTest` from imported Godot resources.",
		"",
		"## Canonical Mapping",
		"",
		"- `idle` -> `Rig_Medium_General/Idle_A`",
		"- `walk` -> `Rig_Medium_MovementBasic/Walking_A`",
		"- `run` -> `Rig_Medium_MovementBasic/Running_A`",
		"- `airborne` -> `Rig_Medium_MovementBasic/Jump_Idle`",
		"- `land` -> `Rig_Medium_MovementBasic/Jump_Land`",
		"- `hit` -> `Rig_Medium_General/Hit_A`",
		"- `eliminated` -> `Rig_Medium_General/Death_A`",
		"- `attack` -> unavailable in audited libraries",
		"- `victory` -> unavailable in audited libraries",
		"",
		"## Libraries",
		"",
	]
	for library_name: String in audit.animations.keys():
		var library: Dictionary = audit.animations[library_name]
		lines.append("### %s" % library_name)
		lines.append("")
		lines.append("- Scene: `%s`" % library.scene_path)
		lines.append("- Clip count: `%d`" % library.clips.size())
		lines.append("")
		for clip_name: String in library.clips.keys():
			var clip: Dictionary = library.clips[clip_name]
			lines.append("- `%s`: length `%.3f`, loop `%s`, tracks `%s`, root motion `%s`, compatible `%s`" % [
				clip.clip_name,
				clip.length,
				clip.loop_mode,
				clip.track_count,
				clip.has_root_motion,
				", ".join(clip.compatible_character_ids),
			])
		lines.append("")
	return "\n".join(lines) + "\n"

func _write_text(path: String, text: String) -> void:
	var file: FileAccess = FileAccess.open(path, FileAccess.WRITE)
	if file == null:
		_errors.append("Could not write report: %s" % path)
		return
	file.store_string(text)
